import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { Plugin } from 'vite';

const LOCALES = ['de', 'en', 'cn', 'ru'] as const;
const LOCALE_INDEX: Record<string, number> = { de: 0, en: 1, cn: 2, ru: 3 };
const MESSAGES_DIR = join(process.cwd(), 'messages');
const OUTPUT_PATH = join(process.cwd(), 'src/lib/messages.svelte.ts');

function loadMessages(): Record<string, string[]> {
	const all: Record<string, string[]> = {};
	for (const file of readdirSync(MESSAGES_DIR).filter((f) => f.endsWith('.json'))) {
		Object.assign(all, JSON.parse(readFileSync(join(MESSAGES_DIR, file), 'utf-8')));
	}
	return all;
}

function generateCode(msgs: Record<string, string[]>): string {
	const messageExports = Object.entries(msgs)
		.map(
			([key, tr]) =>
				`export function ${key}(p?: Record<string, string | number>): string { return _t(${JSON.stringify(tr)}, p); }`
		)
		.join('\n');

	return `// Auto-generated by i18n-plugin. Do not edit.
export const locales = ${JSON.stringify(Array.from(LOCALES))} as const;
export const cookieName = 'LOCALE';
export const cookieMaxAge = 34560000;

let _storage: import('node:async_hooks').AsyncLocalStorage<{ locale: string }> | null | undefined = undefined;

function _readCookie(): string {
  if (typeof document === 'undefined') return 'en';
  const m = document.cookie.match(/(?:^|;\\s*)LOCALE=([^;]+)/);
  return (m && (locales as readonly string[]).includes(m[1])) ? m[1] : 'en';
}

let _currentLocale = $state(_readCookie());

export function getLocale(): string {
  if (_storage) { const s = _storage.getStore(); if (s?.locale) return s.locale; }
  return _currentLocale;
}

export function getLocales() { return locales; }

export function setLocale(l: string): void {
  if (!(locales as readonly string[]).includes(l)) return;
  document.cookie = cookieName + '=' + l + '; path=/; max-age=' + cookieMaxAge;
  _currentLocale = l;
}

export function getTextDirection(locale: string): string {
  return ['ar', 'he', 'fa', 'ur'].includes(locale) ? 'rtl' : 'ltr';
}

export function deLocalizeUrl(url: URL | string): URL {
  return typeof url === 'string' ? new URL(url) : url;
}

export async function runWithLocale<T>(locale: string, fn: () => T | Promise<T>): Promise<T> {
  if (_storage === undefined) {
    try {
      const { AsyncLocalStorage } = await import(/* @vite-ignore */ 'node:async_hooks');
      _storage = new AsyncLocalStorage();
    } catch {
      _storage = null;
    }
  }
  if (_storage) return _storage.run({ locale }, fn) as Promise<T>;
  return fn() as Promise<T>;
}

const _li: Record<string, number> = ${JSON.stringify(LOCALE_INDEX)};

function _t(tr: string[], p?: Record<string, string | number>): string {
  const text = tr[_li[getLocale()] ?? 0] ?? tr[0] ?? '';
  if (!p) return text;
  return text.replace(/\\{(\\w+)\\}/g, (_, k) => String(p[k] ?? '{' + k + '}'));
}

${messageExports}`;
}

function generate(): void {
	const msgs = loadMessages();
	writeFileSync(OUTPUT_PATH, generateCode(msgs));
}

export function i18nPlugin(): Plugin {
	return {
		name: 'i18n-plugin',

		buildStart() {
			generate();
		},

		configureServer(server) {
			generate();
			server.watcher.add(MESSAGES_DIR);
			server.watcher.on('change', (file) => {
				if (file.startsWith(MESSAGES_DIR) && file.endsWith('.json')) {
					generate();
				}
			});
		}
	};
}
